### ISSUE TITLE
Problem with the Markdown engine (Backticks)

### ISSUE THREAD

**Issue by ChubaOraka** [smoldata/smol-chat#13]
There are quite a few issues with the backtick markdown operator, and I suspect there are issues with other markdown operators. If a code block is delimited by backticks in a post, it renders properly on the UI. But when the post is edited, HTML CODE tags (\<code>) appear around the delimited code block.
Additionally, as can be seen on the list item with id [\#message-138](https://chat.smoldata.org/#message-138), the second backtick is escaped for some unknown reason. This ends up interfering with the _border-top_ CSS property of the next message. At first, I suspected that it was due to the forward slashes, but I am yet to find anything in the code that proves my hypothesis.

**Comment by dphiffer** [comment]
I think I figured this one out. It was basically an out-of-order sequence:
1. format .md => .html
2. escape HTML

I reversed it so now it is:
1. escape HTML
2. format .md => .html
